# Generated by Django 4.0.6 on 2022-08-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.user')),
            ],
        ),
    ]
